parameters:
    - name: solutionType
      type: string
      values: 
      - dotnet
      - nodejs
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: string
    - name: developmentFrameworkVersion
      type: string
    - name: buildConfiguration
      type: string
    - name: agentPool
      type: string


jobs:
  - job: Build_DotNet_Package_Job
    displayName: Build .Net Package
    condition: eq(parameter['solutionType'], 'dotnet')
    ${{ if eq(parameters.agentPool, 'null')}}:
      pool:
        vmImage: ${{ parameters.agentPool }}
    steps:

    - template: ../steps/dotnet-framework.yaml
      parameters: 
        developmentFrameworkVersion: ${{ parameters.developmentFrameworkVersion }}
    
    - template: ../steps/dotnet-build.yaml
      parameters: 
        solutionName: ${{ parameters.solutionName }}
        solutionDirectory: ${{ parameters.solutionDirectory }}
        buildConfiguration: ${{ parameters.buildConfiguration }}

  - job: Build_NodeJS_Package_Job
    displayName: Build Node.JS Package
    condition: eq(parameter['solutionType'], 'nodejs')
    ${{ if eq(parameters.agentPool, 'null')}}:
      pool:
        vmImage: ${{ parameters.agentPool }}
    steps:

    - template: ../steps/dotnet-framework.yaml
      parameters: 
        developmentFrameworkVersion: ${{ parameters.developmentFrameworkVersion }}
    
    - template: ../steps/dotnet-build.yaml
      parameters: 
        solutionName: ${{ parameters.solutionName }}
        solutionDirectory: ${{ parameters.solutionDirectory }}
        buildConfiguration: ${{ parameters.buildConfiguration }}