parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: string
    #- name: projectNames
    #  type: object
    - name: buildConfiguration
      type: string

steps:

- task: DotNetCoreCLI@2
  displayName: Restore .Net Project
  inputs:
    command: 'restore'
    projects: "${{ parameters.solutionDirectory }}/**/*.csproj"
    feedsToUse: 'select'
    includeNuGetOrg: true
    
- task: DotNetCoreCLI@2
  displayName: Build .Net Project
  inputs:
    command: 'build'
    projects: "${{ parameters.solutionDirectory }}/**/*.csproj"
    arguments: "--configuration ${{ parameters.buildConfiguration }}"

# - ${{ each projectName in parameters.projectNames.names }}:
- task: DotNetCoreCLI@2
  displayName: UnitTest .Net Project - ${{ projectName }}
  inputs:
    command: 'test'
    projects: "${{ parameters.solutionDirectory }}/${{ projectName }}.UnitTests/${{ projectName }}.UnitTests.csproj"
    testRunTitle: 'Unit Tests'
