parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: string
    - name: buildConfiguration
      type: string

steps:

- task: DotNetCoreCLI@2
  displayName: Restore .Net Project
  inputs:
    command: 'restore'
    projects: "**/*.csproj"
    feedsToUse: 'select'
    includeNuGetOrg: true
    


- task: DotNetCoreCLI@2
  displayName: Build .Net Project
  inputs:
    command: 'build'
    projects: "**/*.csproj"
    arguments: "--configuration ${{ parameters.buildConfiguration }}"

- task: DotNetCoreCLI@2
  displayName: UnitTest .Net Project
  inputs:
    command: 'test'
    projects: "**/${{ parameters.solutionName }}.Tests.csproj"
    testRunTitle: 'Unit Tests'