parameters:
    - name: solutionName
      type: string
    - name: solutionDirectory
      type: object
    - name: projectNames
      type: string
    - name: buildConfiguration
      type: string

steps:

- task: DotNetCoreCLI@2
  displayName: Restore .Net Project
  inputs:
    command: 'restore'
    projects: "${{ parameters.solutionDirectory }}/**/*.csproj"
    feedsToUse: 'select'
    includeNuGetOrg: true
    
- task: DotNetCoreCLI@2
  displayName: Build .Net Project
  inputs:
    command: 'build'
    projects: "${{ parameters.solutionDirectory }}/**/*.csproj"
    arguments: "--configuration ${{ parameters.buildConfiguration }}"
  
#- ${{ each name in parameters.projectNames }}:
#  - task: DotNetCoreCLI@2
#    displayName: UnitTest .Net Project - ${{ name }}
#    inputs:
#      command: 'test'
#      projects: "${{ parameters.solutionDirectory }}/${{ name }}.UnitTests/${{ name }}.UnitTests.csproj"
#      testRunTitle: 'Unit Tests'
