name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - Main
    - feature/*

pr:
  branches:
    include:
    - Main

extends:
  template: ../types/cicd-libraries.yaml
  parameters:
    solutionType:  dotnet #
    agentPool: 'ubuntu-latest'
    settings:
      solutionName:  Example.Solution #
      solutionDirectory: src/sharedlibraries/nuget/Example.Solution 
      developmentFrameworkVersion: 6.0.x #
      buildConfiguration: Release