parameters:
    - name: settings
      type: object

stages:
    - stage: build
      jobs:
      - template: /devops/pipelines/templates/stages/build-packages.yaml
        parameters:
          agentPool: ${{ parameters.settings.agentPool }}
          solutionType: ${{ parameters.settings.solutionType }}
          solutionName: ${{ parameters.settings.solutionName }}
          solutionDirectory: ${{ parameters.settings.solutionDirectory }}
          developmentFrameworkVersion: ${{ parameters.settings.developmentFrameworkVersion }}
          buildConfiguration: ${{ parameters.settings.buildConfiguration }}